### PR TITLE
Fixed #3.

### LINKED ISSUE #3: Can not calculate percentage
in students/admin.py i need to calculate the percentage value for each bar in bar graph. I can't figure out the formula.

### PR DESCRIPTION
**Pull request by Argetan**
I'm not sure if this is what you had in mind but, this solution displays a table with 4 columns.

- The First Column shows the date associated with the fee (on which it was paid, not put in the system).
- The Second Column shows the number of fees that day.
- The Third Column shows how much was paid that day.
- The Fourth Column shows how much that is relatively seen to the rest of the selected period.

### CODE REVIEW

**Comment by Argetan** [comment]
I should note that some of your code might be broken at the moment since I got rid of the `month` and `year` fields and replaced them with a `DateField`.

**Comment by ZeroCoolHacker** [comment]
> I should note that some of your code might be broken at the moment since I got rid of the `month` and `year` fields and replaced them with a `DateField`.

Yeah i think thats better than using the previous fields.
Thank you for the help.

**Comment by Argetan** [comment]
No problem, glad I could help you out 😄

**Comment by ZeroCoolHacker** [comment]
@all-contributors please add @jvdoorn for ideas,userTesting and code

**Pull request merged**
